/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlavoursRouteImport } from './routes/flavours'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as WhereToBuyRouteImport } from './routes/where-to-buy'
import { Route as WhereToFindUsRouteImport } from './routes/where-to-find-us'
import { Route as OccasionsIndexRouteImport } from './routes/occasions/index'
import { Route as OccasionsBirthdayPartiesRouteImport } from './routes/occasions/birthday-parties'
import { Route as OccasionsEventsRouteImport } from './routes/occasions/events'
import { Route as OccasionsSchoolsSportsClubsRouteImport } from './routes/occasions/schools-sports-clubs'
import { Route as OccasionsVillasPoolsideRouteImport } from './routes/occasions/villas-poolside'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursRoute = FlavoursRouteImport.update({
  id: '/flavours',
  path: '/flavours',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereToBuyRoute = WhereToBuyRouteImport.update({
  id: '/where-to-buy',
  path: '/where-to-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereToFindUsRoute = WhereToFindUsRouteImport.update({
  id: '/where-to-find-us',
  path: '/where-to-find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsIndexRoute = OccasionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OccasionsRoute,
} as any)
const OccasionsBirthdayPartiesRoute =
  OccasionsBirthdayPartiesRouteImport.update({
    id: '/birthday-parties',
    path: '/birthday-parties',
    getParentRoute: () => OccasionsRoute,
  } as any)
const OccasionsEventsRoute = OccasionsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => OccasionsRoute,
} as any)
const OccasionsSchoolsSportsClubsRoute =
  OccasionsSchoolsSportsClubsRouteImport.update({
    id: '/schools-sports-clubs',
    path: '/schools-sports-clubs',
    getParentRoute: () => OccasionsRoute,
  } as any)
const OccasionsVillasPoolsideRoute = OccasionsVillasPoolsideRouteImport.update({
  id: '/villas-poolside',
  path: '/villas-poolside',
  getParentRoute: () => OccasionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/occasions': typeof OccasionsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/packs': typeof PacksRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/where-to-find-us': typeof WhereToFindUsRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/events': typeof OccasionsEventsRoute
  '/occasions/schools-sports-clubs': typeof OccasionsSchoolsSportsClubsRoute
  '/occasions/villas-poolside': typeof OccasionsVillasPoolsideRoute
  '/occasions/': typeof OccasionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/our-story': typeof OurStoryRoute
  '/packs': typeof PacksRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/where-to-find-us': typeof WhereToFindUsRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/events': typeof OccasionsEventsRoute
  '/occasions/schools-sports-clubs': typeof OccasionsSchoolsSportsClubsRoute
  '/occasions/villas-poolside': typeof OccasionsVillasPoolsideRoute
  '/occasions': typeof OccasionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/occasions': typeof OccasionsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/packs': typeof PacksRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/where-to-find-us': typeof WhereToFindUsRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/events': typeof OccasionsEventsRoute
  '/occasions/schools-sports-clubs': typeof OccasionsSchoolsSportsClubsRoute
  '/occasions/villas-poolside': typeof OccasionsVillasPoolsideRoute
  '/occasions/': typeof OccasionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/occasions'
    | '/our-story'
    | '/packs'
    | '/where-to-buy'
    | '/where-to-find-us'
    | '/occasions/birthday-parties'
    | '/occasions/events'
    | '/occasions/schools-sports-clubs'
    | '/occasions/villas-poolside'
    | '/occasions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/our-story'
    | '/packs'
    | '/where-to-buy'
    | '/where-to-find-us'
    | '/occasions/birthday-parties'
    | '/occasions/events'
    | '/occasions/schools-sports-clubs'
    | '/occasions/villas-poolside'
    | '/occasions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/occasions'
    | '/our-story'
    | '/packs'
    | '/where-to-buy'
    | '/where-to-find-us'
    | '/occasions/birthday-parties'
    | '/occasions/events'
    | '/occasions/schools-sports-clubs'
    | '/occasions/villas-poolside'
    | '/occasions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FlavoursRoute: typeof FlavoursRoute
  OccasionsRoute: typeof OccasionsRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  PacksRoute: typeof PacksRoute
  WhereToBuyRoute: typeof WhereToBuyRoute
  WhereToFindUsRoute: typeof WhereToFindUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours': {
      id: '/flavours'
      path: '/flavours'
      fullPath: '/flavours'
      preLoaderRoute: typeof FlavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-to-buy': {
      id: '/where-to-buy'
      path: '/where-to-buy'
      fullPath: '/where-to-buy'
      preLoaderRoute: typeof WhereToBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-to-find-us': {
      id: '/where-to-find-us'
      path: '/where-to-find-us'
      fullPath: '/where-to-find-us'
      preLoaderRoute: typeof WhereToFindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/': {
      id: '/occasions/'
      path: '/'
      fullPath: '/occasions/'
      preLoaderRoute: typeof OccasionsIndexRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/birthday-parties': {
      id: '/occasions/birthday-parties'
      path: '/birthday-parties'
      fullPath: '/occasions/birthday-parties'
      preLoaderRoute: typeof OccasionsBirthdayPartiesRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/events': {
      id: '/occasions/events'
      path: '/events'
      fullPath: '/occasions/events'
      preLoaderRoute: typeof OccasionsEventsRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/schools-sports-clubs': {
      id: '/occasions/schools-sports-clubs'
      path: '/schools-sports-clubs'
      fullPath: '/occasions/schools-sports-clubs'
      preLoaderRoute: typeof OccasionsSchoolsSportsClubsRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/villas-poolside': {
      id: '/occasions/villas-poolside'
      path: '/villas-poolside'
      fullPath: '/occasions/villas-poolside'
      preLoaderRoute: typeof OccasionsVillasPoolsideRouteImport
      parentRoute: typeof OccasionsRoute
    }
  }
}

interface OccasionsRouteChildren {
  OccasionsBirthdayPartiesRoute: typeof OccasionsBirthdayPartiesRoute
  OccasionsEventsRoute: typeof OccasionsEventsRoute
  OccasionsSchoolsSportsClubsRoute: typeof OccasionsSchoolsSportsClubsRoute
  OccasionsVillasPoolsideRoute: typeof OccasionsVillasPoolsideRoute
  OccasionsIndexRoute: typeof OccasionsIndexRoute
}

const OccasionsRouteChildren: OccasionsRouteChildren = {
  OccasionsBirthdayPartiesRoute: OccasionsBirthdayPartiesRoute,
  OccasionsEventsRoute: OccasionsEventsRoute,
  OccasionsSchoolsSportsClubsRoute: OccasionsSchoolsSportsClubsRoute,
  OccasionsVillasPoolsideRoute: OccasionsVillasPoolsideRoute,
  OccasionsIndexRoute: OccasionsIndexRoute,
}

const OccasionsRouteWithChildren = OccasionsRoute._addFileChildren(
  OccasionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FlavoursRoute: FlavoursRoute,
  OccasionsRoute: OccasionsRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  PacksRoute: PacksRoute,
  WhereToBuyRoute: WhereToBuyRoute,
  WhereToFindUsRoute: WhereToFindUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
