/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlavoursRouteImport } from './routes/flavours'
import { Route as WhereToBuyRouteImport } from './routes/where-to-buy'
import { Route as OccasionsBirthdayPartiesRouteImport } from './routes/occasions/birthday-parties'
import { Route as OccasionsSchoolsSportsClubsRouteImport } from './routes/occasions/schools-sports-clubs'
import { Route as OccasionsVillasPoolsideRouteImport } from './routes/occasions/villas-poolside'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursRoute = FlavoursRouteImport.update({
  id: '/flavours',
  path: '/flavours',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereToBuyRoute = WhereToBuyRouteImport.update({
  id: '/where-to-buy',
  path: '/where-to-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsBirthdayPartiesRoute =
  OccasionsBirthdayPartiesRouteImport.update({
    id: '/occasions/birthday-parties',
    path: '/occasions/birthday-parties',
    getParentRoute: () => rootRouteImport,
  } as any)
const OccasionsSchoolsSportsClubsRoute =
  OccasionsSchoolsSportsClubsRouteImport.update({
    id: '/occasions/schools-sports-clubs',
    path: '/occasions/schools-sports-clubs',
    getParentRoute: () => rootRouteImport,
  } as any)
const OccasionsVillasPoolsideRoute = OccasionsVillasPoolsideRouteImport.update({
  id: '/occasions/villas-poolside',
  path: '/occasions/villas-poolside',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/schools-sports-clubs': typeof OccasionsSchoolsSportsClubsRoute
  '/occasions/villas-poolside': typeof OccasionsVillasPoolsideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/schools-sports-clubs': typeof OccasionsSchoolsSportsClubsRoute
  '/occasions/villas-poolside': typeof OccasionsVillasPoolsideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/schools-sports-clubs': typeof OccasionsSchoolsSportsClubsRoute
  '/occasions/villas-poolside': typeof OccasionsVillasPoolsideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/where-to-buy'
    | '/occasions/birthday-parties'
    | '/occasions/schools-sports-clubs'
    | '/occasions/villas-poolside'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/where-to-buy'
    | '/occasions/birthday-parties'
    | '/occasions/schools-sports-clubs'
    | '/occasions/villas-poolside'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/where-to-buy'
    | '/occasions/birthday-parties'
    | '/occasions/schools-sports-clubs'
    | '/occasions/villas-poolside'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FlavoursRoute: typeof FlavoursRoute
  WhereToBuyRoute: typeof WhereToBuyRoute
  OccasionsBirthdayPartiesRoute: typeof OccasionsBirthdayPartiesRoute
  OccasionsSchoolsSportsClubsRoute: typeof OccasionsSchoolsSportsClubsRoute
  OccasionsVillasPoolsideRoute: typeof OccasionsVillasPoolsideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours': {
      id: '/flavours'
      path: '/flavours'
      fullPath: '/flavours'
      preLoaderRoute: typeof FlavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-to-buy': {
      id: '/where-to-buy'
      path: '/where-to-buy'
      fullPath: '/where-to-buy'
      preLoaderRoute: typeof WhereToBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/birthday-parties': {
      id: '/occasions/birthday-parties'
      path: '/occasions/birthday-parties'
      fullPath: '/occasions/birthday-parties'
      preLoaderRoute: typeof OccasionsBirthdayPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/schools-sports-clubs': {
      id: '/occasions/schools-sports-clubs'
      path: '/occasions/schools-sports-clubs'
      fullPath: '/occasions/schools-sports-clubs'
      preLoaderRoute: typeof OccasionsSchoolsSportsClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/villas-poolside': {
      id: '/occasions/villas-poolside'
      path: '/occasions/villas-poolside'
      fullPath: '/occasions/villas-poolside'
      preLoaderRoute: typeof OccasionsVillasPoolsideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FlavoursRoute: FlavoursRoute,
  WhereToBuyRoute: WhereToBuyRoute,
  OccasionsBirthdayPartiesRoute: OccasionsBirthdayPartiesRoute,
  OccasionsSchoolsSportsClubsRoute: OccasionsSchoolsSportsClubsRoute,
  OccasionsVillasPoolsideRoute: OccasionsVillasPoolsideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
